version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: bookdb
      MYSQL_ROOT_PASSWORD: kuldeep@123
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: book-service
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/bookdb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kuldeep@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update